### ISSUE TITLE
Typescript definitions?

### ISSUE THREAD

**Issue by leereichardt** [Aleksandr-JS-Developer/purify-html#1]
**Describe the solution you'd like**
Are there any plans to bundle typescript definitions for this package?

**Would you like to implement your proposal on your own using a pull request?**
I can't see the source is committed to this repo, so I don't think a PR would be (easily) possible

**Comment by Aleksandr-JS-Developer** [comment]
@leereichardt, thanks for the issue!

Yes, I have plans to add typescript definitions. Moreover, there are plans to port the entire library to TypeScript.

About PR.
This repo does not have any other code sources.
I'm sorry, it looks like I misled the name of the `lib` folder. Looks like it should be renamed to `src`.
If you want to contribute - feel free to do PR.

**Comment by leereichardt** [comment]
Ah, thanks for that. I'll see if I can generate some basic and useful definition files until it's ported over to TS.

**Comment by Aleksandr-JS-Developer** [comment]
@leereichardt migration to TypeScript is done 🚀
